#!/bin/bash

echo top of bash_profile
pstree -a $PPID

[[ -v _BASH_PROFILE_RUN ]] && {
    echo already been here
    return
}
_BASH_PROFILE_RUN=1

# .()
# {
#     source "$@"
# }
# source()
# {
#     (shopt -oq verbose && echo "# sourcing $*") || true
#     builtin source "$@"
#     (shopt -oq verbose && echo "# leaving $*") || true
# }

# minimal path builder
pathmunge()
{
    [[ :$PATH: != *:$1:* ]] || PATH="$1:$PATH"
}

pathmunge "$HOME/.bin"
pathmunge "$HOME/.local/bin"

export MAILTO=thomas.bozeman@cgifederal.com
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export EDITOR=nvim
export PAGER=less

for item in ~/.bash_profile.d/*; do
    if [[ -f $item && -r $item && $item =~ .*\.(sh|bash)$ ]]; then
        echo sourcing item "$item"
        . "$item"
    else
        echo >&2 "[!] will not source file: $item"
    fi
done
unset item
