# .bash_aliases
# vim: ft=bash

# color aliases
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'
alias tree='tree -C --dirsfirst'
# alias diff='diff --color=auto'

# some aliases based off ls
alias ls='ls --color=auto --ignore-backups --group-directories-first'
alias ll='ls -lhF'
alias la='ls -A'
alias lf='ll -S'
alias lv='ls --sort=v'
alias l='ls -CF'
alias lla='ll -A'
alias lt='ll --sort=t'
alias l.='ls -d .*'
alias ll.='ll -d .*'

# these are most useful with `shopt -s autocd`
# alias ...='../..'
# alias ....='../../..'
# alias .....='../../../..'
_dots=..
_dirs=..
for _ in $(seq 1 20); do
    _dots+=.
    _dirs+=/..
    # sh*llcheck complains about dynamically defining aliases (and when you talk about it)
    # shellcheck disable=SC2139
    alias $_dots=$_dirs
done
unset _dots _dirs

# alias vim='vim -Xp'
# alias vim='nvim'
# alias nvim='nvim -p'
# alias vim='vim -p'
# alias view='view -p'
alias nv=nvim
alias nvimdiff='nvim -d'
alias nvdiff=nvimdiff

alias cat=bat

# common misspellings
alias sl=ls
alias s=ls
alias fl=lf
alias f=lf
alias ivm=vim
alias vmi=vim
alias cdd=cd
alias dfn=dnf
alias qgit=git


# make du and df a bit more readable
alias df='df -h'
alias du='du -shc'

alias dfx='df -h -t xfs'

# make some basic commands default to verbose, interactive, and recursive (if
# not already)
alias mv='mv -vi'
alias cp='cp -vri'
alias rm='rm -vI --one-file-system'

# some aliases for date in a sortable format
alias day='date +%Y-%m-%d'
alias full='date "+%Y.%m.%d-%H.%M.%S"'

# set some default flags
# alias tidy='tidy -f /dev/null -iqmw'
# alias astyle='astyle -sajcn'
# alias find='find 2>/dev/null'
alias nl='nl -ba'
alias make='make -j $(nproc)'
alias figlet='figlet -t'
# alias rgrep='grep -r'
alias vimrc='vim ~/.vimrc'
# alias gvimrc='gvim ~/.gvimrc'
alias aliases='nv ~/.bash_aliases'
alias bashrc='nv ~/.bashrc'
alias nvconfig='nv ~/.config/nvim/lua/config/lazy.lua'
alias nvrc='nv ~/.config/nvim/lua/{plugins/{core,python}.lua,config/{options,keymaps}.lua} +"Neotree show"'
alias rmf='rm -rf'
alias ps='ps -H'
# alias listening='lsof -i -s TCP:Listen'
alias ports='sudo ss -tlnp | column -t'
alias docker-prune='docker system prune -f --volumes'
alias docker-halt='docker container ls -a --format "{{.Names}}" | xargs -r docker container rm -f'
alias docker-scrub='docker-halt && docker-prune'
alias docker-purge='docker-halt && docker-prune -a'
alias loud='BASH_ENV=~/.bash_loud '
alias verbose='BASH_ENV=~/.bash_verbose '
alias xclip='xclip -selection clipboard'

alias curl='curl -w "\n"'

alias http='http --ignore-stdin'

if [[ -f /usr/local/lib/antlr-4.9-complete.jar ]]; then
    alias grun='java -Xmx500M -cp "/usr/local/lib/antlr-4.9-complete.jar:$CLASSPATH" org.antlr.v4.gui.TestRig'
    alias antlr4='java -Xmx500M -cp "/usr/local/lib/antlr-4.9-complete.jar:$CLASSPATH" org.antlr.v4.Tool'
    # alias antlr4='java -Xmx500M -cp "/usr/local/lib/antlr-4.8-complete.jar:$CLASSPATH" org.antlr.v4.Tool'
    # alias antlr4='java -Xmx500M -cp "/usr/local/lib/antlr-4.7-complete.jar:$CLASSPATH" org.antlr.v4.Tool'
fi


# resolve symlinks
alias cd='cd -P'

# maxar specific

# this is a script now
# alias mxcurl='curl -s -H "Authorization: $(token)" -H "Accept: application/json, */*"'
# # bootstrap depends on an old version of yq, so i've installed yq 4 as "yq-4"
# alias yq='yq-4'

alias eureka='eureka -s'

# print out all variables, even if not exported
# sh*llcheck sees `$item` being used, but not defined 🙄
# shellcheck disable=SC2154
alias xenv='compgen -v | grep -v "^_" | sort | while read -r item; do declare -p $item ; done'

# become root, but with all my bells and whistles (not well tested)
alias super='sudo env HOME=$HOME /usr/local/bin/bash --login -i'
