#!/bin/bash
# vim: tabstop=4 shiftwidth=0 expandtab

awsCreds2() {
    # compare program name ($0) against script name (${BASH_SOURCE[0]});
    # if they're the same, we're being executed as a script
    if [[ $0 == "$BASH_SOURCE" ]]; then
        echo >&2 "[!] $BASH_SOURCE must be sourced (not executed)"
        USAGE=1
    fi

    local -a POSITIONAL
    local HELP USAGE FORCE
    while [[ $# -gt 0 ]]; do
        arg=$1 && shift
        case $arg in
            -h | --help) HELP=1 ;;
            -F | --force) FORCE=1 ;;
            -r | --root)
                local ROOT=$1 && shift
                ;;
            -f | --file | --filename)
                local FILENAME=$1 && shift
                ;;
            -*)
                echo >&2 "[X] $BASH_SOURCE: I don't understand $arg"
                USAGE=1
                ;;
            *) POSITIONAL+=("$arg") ;;
        esac
    done

    local name
    for name in PROFILE REGION; do
        ((${#POSITIONAL[@]} > 0)) || break
        local $name="${POSITIONAL[0]}"
        POSITIONAL=("${POSITIONAL[@]:1}")
    done

    # flags from input:
    # 1. explicit PROFILE & REGION?
    # 2. --file passed?
    # 3. --force passed?

    # branch points
    # 1. try read file?
    # 2. file exists (and valid)? -- treated as two separate branch points
    # 4. file and explicit PROFILE & REGION don't match?
    # 5. short-circuit for good cached credentials?

    # possible input combinations:
    # 1: no explicit,  no --file,  no --force:  error
    # 2: yes explicit, no --file,  no --force:  read & write to generated filename
    # 3: no explicit,  yes --file, no --force:  read from file (or error); if reauthenticating, use file's PROFILE & REGION
    # 4: yes explicit, yes --file, no --force:  read from file if exists; error if file and explicit PROFILE & REGION don't match
    # 5: no explicit,  no --file,  yes --force: error
    # 6: yes explicit, no --file,  yes --force: write to generated filename
    # 7: no explicit,  yes --file, yes --force: read from file (or error); reauthenticate using file's PROFILE & REGION
    # 8: yes explicit, yes --file, yes --force: reload using explicit PROFILE & REGION; write to file

    # automatic error: !(explicit | file)
    # try read file?: !(force & explicit)
    # require file exists/valid?: !(explicit)
    # require file matches?: explicit & !(force)
    # short-circuit?: !(force)

    # if we weren't told to force reauthentication with explicit parameters, try to read our file
    #     if our file exists, read it
    #         if our file seems valid...
    #             if we have explicit parameters, compare the parameters
    #                 if they don't match our file, return failure
    #             otherwise, use parameters from our file
    #             if our file's credentials are not expired, and we're not being `--force`d, return success
    #         otherwise, if we don't have explicit parameters, return failure
    #     otherwise, if we don't have explicit parameters, return failure
    # reauthenticate with AWS
    # write the parameters and credentials to our file
    # read our file

    # if we weren't explicitly asked for help, do some checks
    if [[ ! -v HELP ]]; then
        if ((${#POSITIONAL[@]} != 0)); then
            echo >&2 "[!] Too many parameters: ${POSITIONAL[*]}"
            USAGE=1
        fi

        if [[ -v PROFILE && ! -v REGION ]]; then
            echo >&2 "[!] PROFILE and REGION are mutually dependent"
            USAGE=1
        fi

        if [[ ! -v FILENAME && ! -v PROFILE ]]; then
            echo >&2 "[!] Either --file or PROFILE and REGION are required"
            USAGE=1
        fi

        if [[ -v FILENAME && -v ROOT ]]; then
            echo >&2 "[!] --root and --file are mutually exclusive"
            USAGE=1
        fi
    fi

    if [[ -v HELP || -v USAGE ]]; then
        # if USAGE, we've printed other messages already, so print a blank line
        [[ -v USAGE ]] && echo

        # HELP includes the USAGE header
        echo "Set required AWS environment variables, reauthenticating if necessary."
        echo "Usage: source $BASH_SOURCE [OPTIONS] PROFILE REGION"

        # full help output requested
        if [[ -v HELP ]]; then
            command cat <<- EOF

			Parameters:

			PROFILE             The Okta profile (to be passed to gimme-aws-creds).
			REGION              The AWS region to use.

			Options:

			-h | --help         Print this help output and return.
			-F | --force        Do not examine curent or cached credentials; always reload them.
			-r | --root ROOT    The directory root to read & write cached credential files from.
			-f | --file FILE    The specific filename to read and write cached credentials from.

			If --file is pointed to an existing profile file, PROFILE and REGION are not required.

			EOF
        fi

        if [[ -v HELP ]]; then
            return 0
        else
            return 1
        fi
    fi

    [[ -v PROFILE && -v REGION ]] && local EXPLICIT_PARAMS=1

    # if we weren't given an explicit filename, generate one
    if [[ ! -v FILENAME ]]; then
        # set a default ROOT directory if necessary
        local ROOT="${ROOT:-$HOME/.aws}"

        if [[ ! -d $ROOT ]]; then
            echo >&2 "[X] Profile root directory does not exist: $ROOT"
            return 1
        fi

        local FILENAME=$ROOT/${PROFILE?}_${REGION?}_profile
    fi

    # if we weren't told to force reauthentication with explicit parameters, try to read our file
    if [[ ! (-v FORCE && -v EXPLICIT_PARAMS) ]]; then

        # if we don't have explicit parameters and our file doesn't exist, return failure
        # if we don't have explicit parameters and our file is missing required values, return failure
        # if we *do* have explicit parameters, and they don't match our file, return failure
        # if we aren't being `--force`d, and our file's credentials aren't expired, return success

        # if our file exists, read it
        if [[ -f $FILENAME ]]; then
            source "$FILENAME"

            # if our file sets the appropriate parameter variables...
            if [[ -n ${AWS_OKTA_PROFILE-} && -n ${AWS_REGION-} ]]; then
                # if we were given explicit parameters, make sure they match our file
                if [[ -v EXPLICIT_PARAMS ]]; then
                    if [[ $PROFILE != "$AWS_OKTA_PROFILE" || $REGION != "$AWS_REGION" ]]; then
                        echo >&2 "[X] Cached credentials do not match given PROFILE and REGION: $FILENAME"
                        echo >&2 "    Use --force to overwrite"
                        return 1
                    fi
                else
                    # if we were *not* given explicit parameters, use the values from our file
                    local PROFILE=${AWS_OKTA_PROFILE?}
                    local REGION=${AWS_REGION?}
                fi

                if [[ -v FORCE ]]; then
                    # if we were told to force reauthentication, continue
                    true
                elif [[ ! (-v AWS_SESSION_TOKEN && -v AWS_CREDENTIAL_EXPIRATION) ]]; then
                    # otherwise, if our file does not set required credential variables, continue to reauthentication
                    echo "[.] Cached credentials appear invalid: $FILENAME"
                elif [[ ${AWS_CREDENTIAL_EXPIRATION?} < $(date --iso-8601=seconds) ]]; then
                    # otherwise, if our file's credentials appear to be expired, continue to reauthentication
                    echo "[.] Cached credentials appear expired: $FILENAME"
                else
                    # otherwise, return success
                    echo "[.] Cached credentials appear valid (use --force to force reauthentication)"
                    echo "[.] Assumed AWS profile: ${AWS_OKTA_PROFILE?} (${AWS_REGION?}): ${AWS_PROFILE?}"
                    return 0
                fi

            elif [[ ! -v EXPLICIT_PARAMS ]]; then
                # if our file does not set required parameter variables, and we don't have explicit parameters, return failure
                echo >&2 "[X] Profile file seems to be missing required values: $FILENAME"
                echo >&2 "    Pass PROFILE and REGION to reauthenticate"
                return 1
            fi

        elif [[ ! -v EXPLICIT_PARAMS ]]; then
            # if our file doesn't exist, and we don't have explicit parameters, return failure
            echo >&2 "[X] Profile file does not exist: $FILENAME"
            echo >&2 "    Pass PROFILE and REGION to reauthenticate"
            return 1
        fi
    fi

    echo "[.] Reauthenticating with PROFILE=$PROFILE, REGION=$REGION"

    # perform request
    local JSON_RESPONSE
    JSON_RESPONSE=$(gimme-aws-creds --profile="$PROFILE" --output-format=json) || {
        echo >&2 "[X] Failed to gather credentials"
        return 1
    }

    local AWS_PROFILE
    AWS_PROFILE=$(jq -r '.profile.name' <<< "$JSON_RESPONSE") || {
        echo >&2 "[X] Response seems invalid"
        echo >&2 "$JSON_RESPONSE"
        return 1
    }

    echo "[.] Caching credentials to $FILENAME"

    # write file
    command cat <<- EOF > "$FILENAME"
		export AWS_OKTA_PROFILE="$PROFILE"
		export AWS_DEFAULT_PROFILE="$AWS_PROFILE"
		export AWS_PROFILE="$AWS_PROFILE"
		export AWS_REGION="$REGION"
		export AWS_ACCESS_KEY_ID="$(jq -r '.credentials.aws_access_key_id' <<< "$JSON_RESPONSE")"
		export AWS_SECRET_ACCESS_KEY="$(jq -r '.credentials.aws_secret_access_key' <<< "$JSON_RESPONSE")"
		export AWS_SESSION_TOKEN="$(jq -r '.credentials.aws_session_token' <<< "$JSON_RESPONSE")"
		export AWS_SECURITY_TOKEN="$(jq -r '.credentials.aws_security_token' <<< "$JSON_RESPONSE")"
		export AWS_CREDENTIAL_EXPIRATION="$(jq -r '.credentials.expiration' <<< "$JSON_RESPONSE")"
		EOF

    chmod 600 "$FILENAME"

    source "$FILENAME"
    echo "[.] Assumed AWS profile: ${AWS_OKTA_PROFILE?} (${AWS_REGION?}): ${AWS_PROFILE?}"
    return 0
}

awsCreds2 "$@"
