#!/usr/bin/env bash

set -eu

: "${WB_TOOLS:=$HOME/workspace/maxar/wb-team}"
source "$WB_TOOLS/source_all.sh"

COMMAND=${BASH_SOURCE[0]##*/}

[[ $(type -t "$COMMAND") == function ]] || exit 127

"$COMMAND" "$@"
