#!/bin/bash
# color aliases
alias ls='ls --color=auto --hide=*~ --hide=.*~ --group-directories-first'
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'
alias tree='tree -C'

# some aliases based off ls
alias ll='ls -lhF'
alias la='ls -A'
alias lf='ll -S'
alias lv='ls --sort=v'
alias l='ls -CF'
alias lla='ll -A'
alias lt='ll --sort=t'

alias ...='../..'
alias ....='../../..'
alias .....='../../../..'

# because i'm a moron sometimes
alias qgit='git'

# open each file in its own tab
alias vim='vim -Xp'

# common misspellings
alias sl=ls
alias s=ls
alias ivm=vim
alias vmi=vim
alias cdd=cd

# make du and df a bit more readable
alias df='df -h'
alias du='du -hc 2>/dev/null'
alias dfx='df -h -t xfs'

# make some basic commands default to verbose, interactive, and recursive (if
# not already)
alias mv='mv -vi'
alias cp='cp -vri'
alias rm='rm -vI --one-file-system'

# misc
alias rgrep='grep -r'
alias rmf='rm -rf'
alias ps='ps -H'
alias curl='curl -w "\n"'
alias less='less -SR'
