#!/bin/bash

rm -f ~/.profile
rm -f ~/.bashrc
rm -f ~/.vimrc
rm -f ~/.gvimrc
rm -f ~/.inputrc
rm -f ~/.bash_aliases
rm -f ~/.bash_logout
rm -f ~/.gitconfig
rm -f ~/.git-prompt
rm -f ~/.vim
rm -f ~/.tmux.conf
rm -f ~/.tmux-powerline.conf

rm -rf ~/.bin
rm -rf ~/.pymodules
rm -rf ~/.config/htop
rm -rf ~/.config/powerline
