#!/bin/bash -eu

# remove dotfiles (either uninstalling a previous "wireup", or clearing out the initial "skel")

BACKUP_DIR=$HOME/dotfiles
mkdir -p $BACKUP_DIR

function maybe_delete {
    # if it's a symbolic link, nuke it
    # otherwise, move it to $BACKUP_DIR (possibly numbered)
    if [[ -L $1 ]]; then
        rm -f $1
    elif [[ -e $1 ]]; then
        newname=$(basename $1)
        # `${newname##.}` turns ".bashrc" into "bashrc"
        mv --backup=numbered $1 $BACKUP_DIR/${newname##.}
    fi
}

# regular files
maybe_delete ~/.profile
maybe_delete ~/.bashrc
maybe_delete ~/.vimrc
maybe_delete ~/.gvimrc
maybe_delete ~/.inputrc
maybe_delete ~/.bash_aliases
maybe_delete ~/.bash_functions
maybe_delete ~/.bash_logout
maybe_delete ~/.gitconfig
maybe_delete ~/.git-prompt
maybe_delete ~/.vim
maybe_delete ~/.tmux.conf
maybe_delete ~/.tmux-powerline.conf
maybe_delete ~/.ssh/config
maybe_delete ~/.pythonrc.py

# directories
maybe_delete ~/.bin
maybe_delete ~/.config/htop
maybe_delete ~/.config/powerline
maybe_delete ~/.pymodules
