#!/bin/bash

rm -f ~/.profile
rm -f ~/.bashrc
rm -f ~/.vimrc
rm -f ~/.inputrc
rm -f ~/.bash_aliases
rm -f ~/.bin
rm -f ~/.pymodules
rm -f ~/.bash_logout
rm -f ~/.toprc
rm -f ~/.gitconfig
rm -f ~/.git-prompt
rm -f ~/.vim
rm -f ~/.screenrc
