#!/bin/bash

/usr/bin/which rbenv &>/dev/null || return

# generated by `rbenv init -`
# rbenv 1.2.0-70-g4fec76f

export PATH="/home/tbozeman/.rbenv/shims:${PATH}"
export RBENV_SHELL=bash
source '/home/tbozeman/.rbenv/completions/rbenv.bash'
command rbenv rehash 2>/dev/null
rbenv() {
  local command
  command="${1:-}"
  if [ "$#" -gt 0 ]; then
    shift
  fi

  case "$command" in
  rehash|shell)
    eval "$(rbenv "sh-$command" "$@")";;
  *)
    command rbenv "$command" "$@";;
  esac
}
