#!/bin/bash

/usr/bin/which nodenv &>/dev/null || return

# generated by `nodenv init -`
# nodenv 1.4.1

export PATH="$HOME/.nodenv/shims:${PATH}"
export NODENV_SHELL=bash
source "$HOME/.nodenv/libexec/../completions/nodenv.bash"
command nodenv rehash 2>/dev/null
nodenv() {
  local command
  command="${1:-}"
  if [ "$#" -gt 0 ]; then
    shift
  fi

  case "$command" in
  rehash|shell)
    eval "$(nodenv "sh-$command" "$@")";;
  *)
    command nodenv "$command" "$@";;
  esac
}
