# Alacritty config file
# see `man -s 5 alacritty` or [https://alacritty.org/config-alacritty.html] for more

[window]
startup_mode = "Maximized"

[env]
TURBO_MODE = "1"

# [shell]
# program = "/usr/local/bin/bash"
# args = ["--login", "-i"]

[font]
size = 8

[font.normal]
# NOTE: fonts live in ~/.local/share/fonts,
# font config lives in ~/.config/fontconfig/fonts.conf

# ┌────────────────────────────────┐
# │😀😃😄😁🙃😗🤪🤑🤐😏😒🙄🤯🤠😕🙁│
# └────────────────────────────────┘

family = "JetBrains Mono with Fallback"

[colors]
draw_bold_text_with_bright_colors = false

# Colors (Tomorrow Night)

[colors.bright]
black = "#444444"
blue = "#7aa6da"
cyan = "#70c0b1"
green = "#49fa4a"
magenta = "#c397d8"
red = "#e56e73"
white = "#eaeaea"
yellow = "#ffff67"

[colors.normal]
black = "#1d1f21"
blue = "#6192be"
cyan = "#4abeb7"
green = "#72bd68"
magenta = "#a254ab"
red = "#cc5555"
white = "#c5c8c6"
yellow = "#e8e268"

[colors.primary]
background = "#1d1f21"
bright_foreground = "#eaeaea"
dim_foreground = "#828482"
foreground = "#c5c8c6"
