#!/bin/bash

haveexe nodenv || return

# generated by `nodenv init -`
# nodenv 1.4.1

pathmungex PATH "$HOME/.nodenv/shims"
export NODENV_SHELL=bash

sourcepath "$HOME/.nodenv/completions/nodenv.bash"
# shellcheck disable=2218  # i'm not calling the function, i'm calling the executable
command nodenv rehash 2> /dev/null
nodenv()
{
    local command="${1:-}"
    shift || true

    case "$command" in
        rehash | shell)
            eval "$(nodenv "sh-$command" "$@")"
            ;;
        *)
            command nodenv "$command" "$@"
            ;;
    esac
}
