#!/bin/bash

haveexe rbenv || return

# generated by `rbenv init -`
# rbenv 1.2.0-70-g4fec76f

pathmungex PATH "$HOME/.rbenv/shims"
export RBENV_SHELL=bash
sourcepath "$HOME/.rbenv/completions/rbenv.bash"
# shellcheck disable=2218  # i'm not calling the function, i'm calling the executable
command rbenv rehash 2> /dev/null
rbenv()
{
    local command="${1:-}"
    shift || true

    case "$command" in
        rehash | shell) eval "$(rbenv "sh-$command" "$@")" ;;
        *) command rbenv "$command" "$@" ;;
    esac
}
