#!/bin/bash

/usr/bin/which pyenv &>/dev/null || return

eval "$(pyenv init -)"

# generated by `pyenv init -`
# pyenv 2.3.26

# PATH="$(bash --norc -ec 'IFS=:; paths=($PATH);
# for i in ${!paths[@]}; do
# if [[ ${paths[i]} == "'"$HOME/.pyenv/shims"'" ]]; then unset '\''paths[i]'\'';
# fi; done;
# echo "${paths[*]}"')"
# export PATH="$HOME/.pyenv/shims:${PATH}"
# export PYENV_SHELL=bash
# source "$HOME/.pyenv/libexec/../completions/pyenv.bash"
# command pyenv rehash 2>/dev/null
# pyenv() {
#   local command
#   command="${1:-}"
#   if [ "$#" -gt 0 ]; then
#     shift
#   fi
# 
#   case "$command" in
#   rehash|shell)
#     eval "$(pyenv "sh-$command" "$@")"
#     ;;
#   *)
#     command pyenv "$command" "$@"
#     ;;
#   esac
# }
